### ISSUE TITLE
Compressed font & significant print speedup

### ISSUE THREAD

**Issue by eltomjan** [adafruit/Adafruit_ILI9340#18]
Hello all,
I made interesting improvements of the library on my project - cleared most of fonts data by XORing and adding 2 level bitmap fields, so it takes aprox. 1/3 of bitmap version (big fonts) and improved also printing - I am using a pixel stream similar to clear operation - big & slow SPI data are significantly reduced then...
Does anyone want these changes too ?

**Comment by microbuilder** [comment]
Normally, the best approach is to generate a pull request on Github so that other people can review the code and it can potentially be merged in.

If you've never create a PR on Github, you may find this useful: https://help.github.com/articles/creating-a-pull-request/  ... once you've done it once it becomes relatively easy and is the best solution for collaborating on code like this.

**Comment by ladyada** [comment]
this library is deprecated, you can use Adafruit_ILI9341 instead!
